apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todoapp

resources:
  - namespace.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - loadbalancer-service.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: todoapp
  app.kubernetes.io/managed-by: kustomize

images:
  - name: bdlndacr01.azurecr.io/todoapp
    newTag: latest
